import localFont from "next/font/local";
import "./globals.css";

const geistMono = localFont({
  src: "./fonts/ethnocentric_rg.otf",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistMono.variable} antialiased overflow-y-scroll`}
      >
        {children}
      </body>
    </html>
  );
}
